export const convenios =    
 [
    {
        "__type": "ENTIDAD.EClinica",
        "CONVENIO_TIPO_ID": 0,
        "NOMBRE": "Cristo Rey",
        "ID_ENCRIP": "nPbg/Uz9NNE=",
        "BENEFICIO": "Por la aplicación de 1 vacuna séxtuple aplicación de vits.",
        "PUNTO_AUTORIZADO": 1,
        "TELEFONO": "945630007",
        "DIRECCION": "Av. Retablo 1386 Coop. Primavera - Ref. Mercado Santa Rosa",
        "DEPARTAMENTO": null,
        "PROVINCIA": null,
        "LATITUD": null,
        "LONGITUD": null,
        "GEOGRAFIA_ID": 0,
        "USUARIO_ID": 0,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": null,
        "vPARAM2": null,
        "TIPO": null
    },
    {
        "__type": "ENTIDAD.EClinica",
        "CONVENIO_TIPO_ID": 0,
        "NOMBRE": "Clínica Veterinaria García",
        "ID_ENCRIP": "dJfhzr/385M=",
        "BENEFICIO": "50% dscto. en consultas.\\r\\n50% dscto. en castración de gatos machos.\\r\\n50% dscto. en castración en perros machos menores a 10kg 50% dscto. en medición de hematocrito.",
        "PUNTO_AUTORIZADO": 1,
        "TELEFONO": "986886332 / 056-257481",
        "DIRECCION": "Pasaje SeÓr de Luren Mz E Lt 14 1era etapa",
        "DEPARTAMENTO": null,
        "PROVINCIA": null,
        "LATITUD": null,
        "LONGITUD": null,
        "GEOGRAFIA_ID": 0,
        "USUARIO_ID": 0,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": null,
        "vPARAM2": null,
        "TIPO": null
    },
    {
        "__type": "ENTIDAD.EClinica",
        "CONVENIO_TIPO_ID": 0,
        "NOMBRE": "Tienda de animales",
        "ID_ENCRIP": "snLDW35BmZ4=",
        "BENEFICIO": "por cada 3 baños 1 consulta gratis ",
        "PUNTO_AUTORIZADO": 0,
        "TELEFONO": "971033219",
        "DIRECCION": "Cooperativa mz B lt 7",
        "DEPARTAMENTO": null,
        "PROVINCIA": null,
        "LATITUD": null,
        "LONGITUD": null,
        "GEOGRAFIA_ID": 0,
        "USUARIO_ID": 0,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": null,
        "vPARAM2": null,
        "TIPO": null
    },
    {
        "__type": "ENTIDAD.EClinica",
        "CONVENIO_TIPO_ID": 0,
        "NOMBRE": "Zona Mascota",
        "ID_ENCRIP": "SNp7tbCBwCE=",
        "BENEFICIO": "20% dscto en desparasitación canina y felina, los miércoles baño de gatos S/20.00; todas las vacunas incluyen desparasitación gratis; 20% dscto en la primera consulta",
        "PUNTO_AUTORIZADO": 1,
        "TELEFONO": "957503437",
        "DIRECCION": "Jr. Atahualpa 388 Urb. El Trebol",
        "DEPARTAMENTO": null,
        "PROVINCIA": null,
        "LATITUD": null,
        "LONGITUD": null,
        "GEOGRAFIA_ID": 0,
        "USUARIO_ID": 0,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": null,
        "vPARAM2": null,
        "TIPO": null
    },
    {
        "__type": "ENTIDAD.EClinica",
        "CONVENIO_TIPO_ID": 0,
        "NOMBRE": "Clínica Veterinaria Vet House",
        "ID_ENCRIP": "rRlL9v2BIN4=",
        "BENEFICIO": "20% dscto en baños y dsctos en consultas",
        "PUNTO_AUTORIZADO": 1,
        "TELEFONO": "997313789 / 999554480 / 523-2647",
        "DIRECCION": "Av. Las Palmeras 4019",
        "DEPARTAMENTO": null,
        "PROVINCIA": null,
        "LATITUD": null,
        "LONGITUD": null,
        "GEOGRAFIA_ID": 0,
        "USUARIO_ID": 0,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": null,
        "vPARAM2": null,
        "TIPO": null
    },
    {
        "__type": "ENTIDAD.EClinica",
        "CONVENIO_TIPO_ID": 0,
        "NOMBRE": "Pet Stop",
        "ID_ENCRIP": "Bt/pDETNl6c=",
        "BENEFICIO": "20% dscto consultas generales, 10% dscto consultas (reproducción, neonalología y pediatría), 1era visita desparasitación gratuita",
        "PUNTO_AUTORIZADO": 1,
        "TELEFONO": "262-3042 / 982104055",
        "DIRECCION": "Av. Brasil 2483",
        "DEPARTAMENTO": null,
        "PROVINCIA": null,
        "LATITUD": null,
        "LONGITUD": null,
        "GEOGRAFIA_ID": 0,
        "USUARIO_ID": 0,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": null,
        "vPARAM2": null,
        "TIPO": null
    },
    {
        "__type": "ENTIDAD.EClinica",
        "CONVENIO_TIPO_ID": 0,
        "NOMBRE": "Mis 3 cachorros",
        "ID_ENCRIP": "Ze6S+RmhZCY=",
        "BENEFICIO": "Dscto del 10% en todos los servicios - no incluye con tarjetas de crédito",
        "PUNTO_AUTORIZADO": 0,
        "TELEFONO": "930556828",
        "DIRECCION": "Av. Lima 153",
        "DEPARTAMENTO": null,
        "PROVINCIA": null,
        "LATITUD": null,
        "LONGITUD": null,
        "GEOGRAFIA_ID": 0,
        "USUARIO_ID": 0,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": null,
        "vPARAM2": null,
        "TIPO": null
    }
    ]