export const services = [
    {
        "__type": "ENTIDAD.ESolicitud",
        "ID": 0,
        "SOLICITUD_ID": 0,
        "ID_ENCRIP": "SddKREJbUSk=",
        "SOLICITUD_ID_ENCRIP": null,
        "ID_MSC_ENCRIP": null,
        "FECHA_SOL": null,
        "TOTAL": 0,
        "PRECIO": 0,
        "CANTIDAD": 0,
        "USUARIO_ID": 0,
        "USUARIO": 0,
        "MASCOTA_ID": 0,
        "MASCOTA": "Tiger",
        "DNI": "13825757",
        "EMAIL": "loanachumacero0805@gmail.com",
        "PROPIETARIO": "Loana ",
        "TELEFONO": "967295679",
        "ESTADO": 1,
        "SOL_TOMADA": 0,
        "EST_DSC": null,
        "NOM_REP": "",
        "APE_REP": "",
        "TEL_REP": "",
        "DNI_REP": "",
        "DIRECCION": "",
        "REFERENCIA": "",
        "GEOGRAFIA_ID": 0,
        "DEPARTAMENTO": "",
        "PROVINCIA": "",
        "DISTRITO": "",
        "COMENTARIO": null,
        "FOTO": null,
        "ENVIO": 0,
        "FEC_INI": null,
        "FEC_FIN": null,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": "04/07/2024",
        "vPARAM2": " ",
        "TIPO": "Se registro en la web (Preregistro) (Precio: 0)"
    },
    {
        "__type": "ENTIDAD.ESolicitud",
        "ID": 0,
        "SOLICITUD_ID": 0,
        "ID_ENCRIP": "6nldW6dd1Og=",
        "SOLICITUD_ID_ENCRIP": null,
        "ID_MSC_ENCRIP": null,
        "FECHA_SOL": null,
        "TOTAL": 0,
        "PRECIO": 0,
        "CANTIDAD": 0,
        "USUARIO_ID": 0,
        "USUARIO": 0,
        "MASCOTA_ID": 0,
        "MASCOTA": "Simba",
        "DNI": "07004611",
        "EMAIL": "jhomirazalve@gmail.com",
        "PROPIETARIO": "Jhomira Maricelia ",
        "TELEFONO": "995882592",
        "ESTADO": 1,
        "SOL_TOMADA": 0,
        "EST_DSC": null,
        "NOM_REP": "",
        "APE_REP": "",
        "TEL_REP": "",
        "DNI_REP": "",
        "DIRECCION": "",
        "REFERENCIA": "",
        "GEOGRAFIA_ID": 0,
        "DEPARTAMENTO": "",
        "PROVINCIA": "",
        "DISTRITO": "",
        "COMENTARIO": null,
        "FOTO": null,
        "ENVIO": 0,
        "FEC_INI": null,
        "FEC_FIN": null,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": "04/07/2024",
        "vPARAM2": " ",
        "TIPO": "Se registro en la web (Preregistro) (Precio: 0)"
    },
    {
        "__type": "ENTIDAD.ESolicitud",
        "ID": 0,
        "SOLICITUD_ID": 0,
        "ID_ENCRIP": "uMJ5LLL1KTA=",
        "SOLICITUD_ID_ENCRIP": null,
        "ID_MSC_ENCRIP": null,
        "FECHA_SOL": null,
        "TOTAL": 0,
        "PRECIO": 0,
        "CANTIDAD": 0,
        "USUARIO_ID": 0,
        "USUARIO": 0,
        "MASCOTA_ID": 0,
        "MASCOTA": "Akira valentina ",
        "DNI": "78616692",
        "EMAIL": "pturpialfsb@gmail.com Antoniojmdlr1197@gmail.com",
        "PROPIETARIO": "Roxana y Antonio",
        "TELEFONO": "922 302 323 934 024 533",
        "ESTADO": 1,
        "SOL_TOMADA": 0,
        "EST_DSC": null,
        "NOM_REP": "",
        "APE_REP": "",
        "TEL_REP": "",
        "DNI_REP": "",
        "DIRECCION": "",
        "REFERENCIA": "",
        "GEOGRAFIA_ID": 0,
        "DEPARTAMENTO": "",
        "PROVINCIA": "",
        "DISTRITO": "",
        "COMENTARIO": null,
        "FOTO": null,
        "ENVIO": 0,
        "FEC_INI": null,
        "FEC_FIN": null,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": "04/07/2024",
        "vPARAM2": " ",
        "TIPO": "Se registro en la web (Preregistro) (Precio: 0)"
    },
    {
        "__type": "ENTIDAD.ESolicitud",
        "ID": 0,
        "SOLICITUD_ID": 0,
        "ID_ENCRIP": "gknTgYeBPR8=",
        "SOLICITUD_ID_ENCRIP": null,
        "ID_MSC_ENCRIP": null,
        "FECHA_SOL": null,
        "TOTAL": 0,
        "PRECIO": 0,
        "CANTIDAD": 0,
        "USUARIO_ID": 0,
        "USUARIO": 0,
        "MASCOTA_ID": 0,
        "MASCOTA": "Rey",
        "DNI": "57702594",
        "EMAIL": "yailucilc@gmail.com",
        "PROPIETARIO": "Rey ",
        "TELEFONO": "916690018",
        "ESTADO": 1,
        "SOL_TOMADA": 0,
        "EST_DSC": null,
        "NOM_REP": "",
        "APE_REP": "",
        "TEL_REP": "",
        "DNI_REP": "",
        "DIRECCION": "",
        "REFERENCIA": "",
        "GEOGRAFIA_ID": 0,
        "DEPARTAMENTO": "",
        "PROVINCIA": "",
        "DISTRITO": "",
        "COMENTARIO": null,
        "FOTO": null,
        "ENVIO": 0,
        "FEC_INI": null,
        "FEC_FIN": null,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": "03/07/2024",
        "vPARAM2": " ",
        "TIPO": "Se registro en la web (Preregistro) (Precio: 0)"
    },
    {
        "__type": "ENTIDAD.ESolicitud",
        "ID": 0,
        "SOLICITUD_ID": 0,
        "ID_ENCRIP": "AcUTidaADuI=",
        "SOLICITUD_ID_ENCRIP": null,
        "ID_MSC_ENCRIP": null,
        "FECHA_SOL": null,
        "TOTAL": 0,
        "PRECIO": 0,
        "CANTIDAD": 0,
        "USUARIO_ID": 0,
        "USUARIO": 0,
        "MASCOTA_ID": 0,
        "MASCOTA": "Duque Russell",
        "DNI": "81695994",
        "EMAIL": "alonzo.almeidaa@gmail.com",
        "PROPIETARIO": "Alonzo",
        "TELEFONO": "917073152",
        "ESTADO": 1,
        "SOL_TOMADA": 0,
        "EST_DSC": null,
        "NOM_REP": "",
        "APE_REP": "",
        "TEL_REP": "",
        "DNI_REP": "",
        "DIRECCION": "",
        "REFERENCIA": "",
        "GEOGRAFIA_ID": 0,
        "DEPARTAMENTO": "",
        "PROVINCIA": "",
        "DISTRITO": "",
        "COMENTARIO": null,
        "FOTO": null,
        "ENVIO": 0,
        "FEC_INI": null,
        "FEC_FIN": null,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": "03/07/2024",
        "vPARAM2": " ",
        "TIPO": "Se registro en la web (Preregistro) (Precio: 0)"
    },
    {
        "__type": "ENTIDAD.ESolicitud",
        "ID": 0,
        "SOLICITUD_ID": 0,
        "ID_ENCRIP": "1VHrs+TmRyw=",
        "SOLICITUD_ID_ENCRIP": null,
        "ID_MSC_ENCRIP": null,
        "FECHA_SOL": null,
        "TOTAL": 0,
        "PRECIO": 0,
        "CANTIDAD": 0,
        "USUARIO_ID": 0,
        "USUARIO": 0,
        "MASCOTA_ID": 0,
        "MASCOTA": "DIXYLEE",
        "DNI": "59177522",
        "EMAIL": "miriamyyamile@gmail.com",
        "PROPIETARIO": "Miriam del Rocio ",
        "TELEFONO": "964980816",
        "ESTADO": 1,
        "SOL_TOMADA": 0,
        "EST_DSC": null,
        "NOM_REP": "",
        "APE_REP": "",
        "TEL_REP": "",
        "DNI_REP": "",
        "DIRECCION": "",
        "REFERENCIA": "",
        "GEOGRAFIA_ID": 0,
        "DEPARTAMENTO": "",
        "PROVINCIA": "",
        "DISTRITO": "",
        "COMENTARIO": null,
        "FOTO": null,
        "ENVIO": 0,
        "FEC_INI": null,
        "FEC_FIN": null,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": "03/07/2024",
        "vPARAM2": " ",
        "TIPO": "Se registro en la web (Preregistro) (Precio: 0)"
    },
    {
        "__type": "ENTIDAD.ESolicitud",
        "ID": 0,
        "SOLICITUD_ID": 0,
        "ID_ENCRIP": "TT7xOCtzmdk=",
        "SOLICITUD_ID_ENCRIP": null,
        "ID_MSC_ENCRIP": null,
        "FECHA_SOL": null,
        "TOTAL": 0,
        "PRECIO": 0,
        "CANTIDAD": 0,
        "USUARIO_ID": 0,
        "USUARIO": 0,
        "MASCOTA_ID": 0,
        "MASCOTA": "Nala AKIRA",
        "DNI": "80376703",
        "EMAIL": "josecaballerovicente9@gmail.com",
        "PROPIETARIO": "Jose luis",
        "TELEFONO": "928203791",
        "ESTADO": 1,
        "SOL_TOMADA": 0,
        "EST_DSC": null,
        "NOM_REP": "",
        "APE_REP": "",
        "TEL_REP": "",
        "DNI_REP": "",
        "DIRECCION": "",
        "REFERENCIA": "",
        "GEOGRAFIA_ID": 0,
        "DEPARTAMENTO": "",
        "PROVINCIA": "",
        "DISTRITO": "",
        "COMENTARIO": null,
        "FOTO": null,
        "ENVIO": 0,
        "FEC_INI": null,
        "FEC_FIN": null,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": "03/07/2024",
        "vPARAM2": " ",
        "TIPO": "Se registro en la web (Preregistro) (Precio: 0)"
    },
    {
        "__type": "ENTIDAD.ESolicitud",
        "ID": 0,
        "SOLICITUD_ID": 0,
        "ID_ENCRIP": "xpjxxztLYN4=",
        "SOLICITUD_ID_ENCRIP": null,
        "ID_MSC_ENCRIP": null,
        "FECHA_SOL": null,
        "TOTAL": 0,
        "PRECIO": 0,
        "CANTIDAD": 0,
        "USUARIO_ID": 0,
        "USUARIO": 0,
        "MASCOTA_ID": 0,
        "MASCOTA": "Lulu",
        "DNI": "87432295",
        "EMAIL": "susanagaetesara@gmail.com",
        "PROPIETARIO": "Susana Elena",
        "TELEFONO": "936960895",
        "ESTADO": 1,
        "SOL_TOMADA": 0,
        "EST_DSC": null,
        "NOM_REP": "",
        "APE_REP": "",
        "TEL_REP": "",
        "DNI_REP": "",
        "DIRECCION": "",
        "REFERENCIA": "",
        "GEOGRAFIA_ID": 0,
        "DEPARTAMENTO": "",
        "PROVINCIA": "",
        "DISTRITO": "",
        "COMENTARIO": null,
        "FOTO": null,
        "ENVIO": 0,
        "FEC_INI": null,
        "FEC_FIN": null,
        "CODIGO": null,
        "DESCRIPCION": null,
        "OPCION": 0,
        "vPARAM1": "02/07/2024",
        "vPARAM2": " ",
        "TIPO": "Se registro en la web (Preregistro) (Precio: 0)"
    },
]